name: Build and Upload iOS IPA

on:
  workflow_dispatch: # run manually
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      # Archive app
      - name: Archive app
        run: |
          xcodebuild \
            -project Tank-IOS.xcodeproj \
            -scheme Unity-iPhone \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/TankIOS.xcarchive archive \
            -allowProvisioningUpdates

      # Export IPA for App Store
      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/TankIOS.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build/output \
            -allowProvisioningUpdates

      # Upload to TestFlight/App Store using Apple ID + App-specific password
      - name: Upload IPA to App Store Connect
        run: |
          xcrun altool --upload-app \
            -f build/output/*.ipa \
            -t ios \
            -u "${{ secrets.APPLE_ID }}" \
            -p "${{ secrets.APPLE_PASSWORD }}"
