name: Build and Upload iOS IPA (API Key)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      # Archive with automatic signing (API key handles auth)
      - name: Archive app
        run: |
          xcodebuild \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/TankIOS.xcarchive archive \
            DEVELOPMENT_TEAM=C677KJH544 \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates

      # Export IPA
      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/TankIOS.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build/output \
            -allowProvisioningUpdates

      # Upload IPA with API Key
      - name: Upload IPA to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/output/*.ipa
          issuer-id: ${{ secrets.APP_STORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APP_STORE_KEY_ID }}
          api-private-key: ${{ secrets.APP_STORE_API_KEY }}

      # Save IPA as GitHub artifact (optional)
      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tank-iOS-IPA
          path: build/output/*.ipa
