name: Build and Upload iOS IPA (Auto-Signing)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      # Archive app with Automatic signing
      - name: Archive app
        run: |
          xcodebuild \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/TankIOS.xcarchive archive \
            DEVELOPMENT_TEAM=C677KJH544 \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates

      # Export IPA
      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/TankIOS.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build/output \
            -allowProvisioningUpdates

      # Upload IPA to App Store Connect
      - name: Upload IPA to App Store Connect
        run: |
          xcrun altool --upload-app \
            -f build/output/*.ipa \
            -t ios \
            -u "${{ secrets.APPLE_ID }}" \
            -p "${{ secrets.APPLE_PASSWORD }}"

      # Optional: Save IPA as GitHub artifact
      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tank-iOS-IPA
          path: build/output/*.ipa
